version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Qatar
    open-pull-requests-limit: 5
    labels: [dependencies, go]
    commit-message:
      prefix: deps(go)
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Qatar
    labels: [dependencies, github-actions]
    commit-message:
      prefix: ci(deps)
      include: scope
